// Checklist content. Tags: 'ev' = backed by a cited source (number = source index), 'lo' = common practice.
window.PLAN = {
  daily: {label:'Daily', items:[
    ['sleep','Get 7+ hours of sleep','Sleep is when focus and memory recover. Set a fixed wake time.','ev','14'],
    ['move','Move for 20 to 30 minutes','A walk or workout counts. Adds up to the weekly 150 minutes and sharpens thinking for a few hours after.','ev','15'],
    ['plan','Write tomorrow\'s if-then plan','One line per task: "If it is 9:00, then I send three tailored applications."','ev','12'],
    ['apply','Send 3 tailored applications to roles posted in the last 72 hours','Match the resume version (software, IT or Scrum) to the post and mirror its top 3 skills.','ev','11'],
    ['tie','Make 1 networking touch with a moderately weak tie','A former coworker, classmate or meetup contact. Comment on a post, send a thank-you or ask a quick question.','ev','7'],
    ['skill','Do 45 minutes of focused skill practice','One target at a time: an AI feature, a cloud service or interview algorithms. Write down what you learned.','lo',''],
    ['rep','Do 1 interview rep out loud','Explain one coding problem or tell one STAR story in under 2 minutes.','ev','11'],
    ['log','Spend 10 minutes logging the day','Update the job tracker and write one thing that went well. Seeing progress builds confidence.','ev','11'],
  ]},
  weekly: {label:'Weekly', items:[
    ['meetup','Go to 1 in-person Austin tech event','Meetups grow the weak ties that matter most in tech. Aim to leave with 2 new names.','ev','7'],
    ['referral','Ask for 2 referrals at target companies','Ask people you have talked with first. Send them the job link and a 3-line summary of your fit.','ev','6'],
    ['ship','Ship 1 visible improvement and post about it','A feature, a fix or a demo on GitHub, then a short LinkedIn post on what you built and why.','lo',''],
    ['mock','Do 1 mock interview','With a friend, a peer site or a Workforce Solutions coach. Get feedback on how you come across.','ev','11'],
    ['funnel','Review your job search numbers','Applications, replies, screens and interviews. Change one thing that is not working.','ev','11'],
    ['strength','Hit 150 active minutes and 2 strength days','Check the week\'s total on Sunday and fill any gap.','ev','15'],
    ['people','Spend real time with a friend or family member','A call or a meal, without your phone. Good relationships protect health over the long run.','ev','16'],
    ['money','Do a 15-minute money check','Review spending and move something into the emergency fund, even a small amount.','ev','17'],
    ['school','Block time for MS coursework','Put the hours on the calendar before the week starts.','lo',''],
    ['review','Do a weekly review and plan next week\'s if-thens','What worked, what did not and the top 3 goals for next week.','ev','12'],
  ]},
  monthly: {label:'Monthly', items:[
    ['targets','Refresh a list of 20 target companies','Mix software, healthcare IT, semiconductor and manufacturing IT and fintech. Start with Built In Austin.','ev','10'],
    ['wfs','Use Workforce Solutions Capital Area once','Book a coach session, attend a hiring event or ask about a training scholarship.','ev','8'],
    ['resume','Update your resumes with new results','Add numbers from new projects. Note which version gets the most replies.','lo',''],
    ['info','Have 1 informational interview','Talk with someone one or two levels ahead in a role you want. Ask how they got hired.','ev','6'],
    ['write','Publish 1 technical write-up or demo','A post, README or short video that shows how you think. It gives contacts something to share.','lo',''],
    ['market','Check the Austin market data','Look at BLS and TWC numbers and 20 fresh postings. Note which skills keep showing up.','ev','1'],
    ['fund','Check emergency fund progress','Track months of expenses covered. The goal is 3 to 6 months.','ev','17'],
  ]},
  quarterly: {label:'Quarterly', items:[
    ['cert','Reach 1 certification milestone','Pass an exam or finish a course. ACC and Workforce Solutions list funding for AWS and other certifications.','ev','9'],
    ['project','Build 1 portfolio project aimed at local demand','Favor AI integration, cloud or security. Record a demo like the others.','ev','4'],
    ['gap','Do a skills gap audit','Compare your skills with 20 Austin postings and pick the top 2 gaps for next quarter.','ev','1'],
    ['lanes','Re-pick your target roles from the data','Compare reply rates for software, IT support, QA and Scrum roles and lean into what is working.','ev','11'],
    ['dormant','Reconnect with 10 old contacts','Past coworkers, classmates and teammates. Share an update and ask about theirs.','ev','7'],
    ['writing','If the search feels heavy, do a 5-day writing reset','20 minutes a day for 5 days, writing about your thoughts and feelings on the search.','ev','13'],
    ['checkup','Book any health or dental visits you are due for','Keep the basics handled so they do not pile up.','lo',''],
  ]},
  yearly: {label:'Yearly', items:[
    ['vision','Write a 1-page vision and 3 goals for the year','Break each goal into quarterly milestones and put the first one on the calendar.','ev','12'],
    ['pay','Benchmark your pay','Compare against Austin salary guides and postings before any review or offer talk.','lo',''],
    ['overhaul','Overhaul your resume and LinkedIn, and refresh references','Rewrite from scratch around your best 3 results of the year.','lo',''],
    ['physical','Get an annual physical and eye exam','Prevention is cheaper than repair.','lo',''],
    ['finance','Do taxes and an annual money plan','Set savings and retirement targets. Texas has no state income tax, so focus on federal.','lo',''],
    ['learn','Set a yearly learning goal','For example a set of MS courses, a certification or a new language, and track it quarterly.','lo',''],
    ['give','Mentor or volunteer with tech skills','Helping others builds skills and a wider network at the same time.','ev','7'],
    ['retro','Write a year-in-review','List what moved you forward and what to drop next year.','lo',''],
  ]},
};
